#==========================================================
#= Articoli Web Service - Autenticazione JWT
#==========================================================
server:
  port: 5051

spring:

  application:
    name: ArticoliWebService

  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


#==========================================================
# Opzioni Accesso Servizio gestuser
#==========================================================
gestuser:
  srvUrl: http://localhost:8100/api/utenti/cerca/userid/
  userId: ReadUser
  password: BimBumBam_2018

# ==============================================================
# = Proprietà Livello Log
# = Default ERROR, WARN e INFO
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ==============================================================
logging:
  file:
    name: '/Users/antonio.carnevale/Documents/Repository/Microservices/logs/ArtWebApi.log' # file inserito nella cartella logs
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    # Livello di log specifico
    org.springframework.security: DEBUG
    org.hibernate: INFO
    org.springframework.web: INFO
    com.xantrix.webapp.controller: INFO
    com.xantrix.webapp.feign.PriceClient: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

# ==============================================================
# = Feign Parameters
# ==============================================================
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        connect-timeout: 300000 # 5 minuti
        read-timeout: 300000

# ==============================================================
# = Configurazione Actuator
# ==============================================================
management:
  endpoints:
    web:
      exposure:
        include: '*'

# ==============================================================
# = Eureka Properties
# ==============================================================

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:BimBumBam_2018@localhost:8761/eureka/,http://user:BimBumBam_2018@localhost:8762/eureka/,http://user:BimBumBam_2018@localhost:8763/eureka/
