name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (skip tests)
      run: mvn clean install -DskipTests

    # Costruisci l'immagine Docker
    - name: Build Docker image
      run: docker build -t local-image/test-app:latest .

    # Salva l'immagine Docker in un file tar con estensione diversa
    - name: Save Docker image to file
      run: docker save -o my-docker-image.dockerimage local-image/test-app:latest

    # Carica il file come artifact per poterlo scaricare
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-tar
        path: articoli-service.tar
